FROM node:20-alpine as build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . ./
ARG NX_API_URL
ENV NX_API_URL=${NX_API_URL}
RUN yarn build client --configuration=production

FROM nginx:alpine
COPY --from=build /usr/src/app/dist/apps/client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
