FROM node:20-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY package.json yarn.lock ./
COPY prisma/ ./prisma/
RUN yarn install --frozen-lockfile --production=false
CMD ["npx", "prisma", "migrate", "deploy"]
