name: Client
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and Yarn
        uses: ./.github/actions/setup-node-yarn
      - name: Check Lint
        run: yarn lint client
      - name: Test
        run: yarn test:client --codeCoverage --verbose
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
